[config]
version_check = false

[config.wallpaper]
command = "swww img --transition-type center {{image}}"
set = true

[templates.waybar]
input_path = './templates/colors.css'
output_path = '~/.config/waybar/colors.css'
post_hook = 'pkill -SIGUSR2 waybar'

[templates.starship]
input_path = './templates/starship.toml'
output_path = '~/.config/starship.toml'

[templates.rofi]
input_path = './templates/colors.rasi'
output_path = '~/.config/rofi/colors.rasi'

[templates.hyprland]
input_path = './templates/hyprland.conf'
output_path = '~/.config/hypr/colors.conf'
post_hook = 'hyprctl reload'

[templates.mako]
input_path = './templates/mako.ini'
output_path = '~/.config/mako/config'
post_hook = '/home/asif/.config/matugen/post_scripts/set_mako_opacity.sh && makoctl reload'

[templates.btop]
input_path = './templates/btop.theme'
output_path = '~/.config/btop/themes/current.theme'

[templates.yazi]
input_path = './templates/yazi-theme.toml'
output_path = '~/.config/yazi/theme.toml'

[templates.cava]
input_path = './templates/zathurarc'
output_path = '~/.config/zathura/zathurarc'

[templates.gtk4]
input_path = './templates/gtk4.css'
output_path = '~/.config/gtk-4.0/gtk-colors.css'
post_hook = 'rm -f ~/.config/gtk-4.0/gtk.css && cat ~/.config/gtk-4.0/gtk-base.css ~/.config/gtk-4.0/gtk-colors.css > ~/.config/gtk-4.0/gtk.css'

[templates.gtk3]
input_path = './templates/gtk3.css'
output_path = '~/.config/gtk-3.0/gtk-colors.css'
post_hook = 'cat ~/.config/gtk-3.0/gtk-base.css ~/.config/gtk-3.0/gtk-colors.css > ~/.config/gtk-3.0/gtk.css && systemctl --user restart xdg-desktop-portal-gtk'

[templates.cody]
input_path = './templates/cody-theme.toml'
output_path = '~/.config/cody/theme.toml'
post_hook = "sh -lc 'pgrep -f \"^/home/asif/Projects/lumen/cody/.venv/bin/python -m cody$\" | xargs -r kill -USR1'"
