-- generated by matugen (templates/background.lua): backgrounds follow the wallpaper palette.
-- `update = true` only changes bg and keeps the colorscheme's other attributes (fg, bold, ...).
local function bg(name, color)
	vim.api.nvim_set_hl(0, name, { bg = color, update = true })
end

bg("Normal", "{{colors.background.default.hex}}")
bg("CursorLine", "{{colors.surface_container.default.hex}}")
bg("CursorColumn", "{{colors.surface_container.default.hex}}")
bg("ColorColumn", "{{colors.surface_container.default.hex}}")
bg("Folded", "{{colors.surface_container_low.default.hex}}")
