format = """
[░▒▓](#a9b665)\
[ 󰣇 ](bg:#a9b665 fg:#585a36)\
[](bg:#89b482 fg:#a9b665)\
$directory\
[](fg:#89b482 bg:#d8a657)\
$git_branch\
$git_status\
[](fg:#d8a657 bg:#32302f)\
$python\
$nodejs\
$java\
$rust\
$golang\
$php\
[](fg:#32302f bg:#282828)\
\n~> """

[directory]
style = "fg:#475d44 bg:#89b482"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
"study" = "󱉟 "
"work" = "󰦑 "

[git_branch]
symbol = ""
style = "bg:#d8a657"
format = '[[ $symbol $branch ](fg:#795f34 bg:#d8a657)]($style)'

[git_status]
style = "bg:#d8a657"
format = '[[($all_status$ahead_behind )](fg:#795f34 bg:#d8a657)]($style)'

[nodejs]
symbol = ""
style = "bg:#32302f"
format = '[[ $symbol ($version) ](fg:#b8bb26 bg:#32302f)]($style)'

[rust]
symbol = ""
style = "bg:#32302f"
format = '[[ $symbol ($version) ](fg:#d3869b bg:#32302f)]($style)'

[java]
symbol = "󰬷"
style = "bg:#32302f"
format = '[[ $symbol ($version) ](fg:#d3869b bg:#32302f)]($style)'

[golang]
symbol = ""
style = "bg:#32302f"
format = '[[ $symbol ($version) ](fg:#795f34 bg:#32302f)]($style)'

[php]
symbol = ""
style = "bg:#32302f"
format = '[[ $symbol ($version) ](fg:#8ec07c bg:#32302f)]($style)'

[python]
symbol = " "                        # Python icon (can be anything)
style = "fg:#74706d bg:#32302f"     # Gruvbox-style color
format = '[[ $symbol($virtualenv) ](fg:#74706d bg:#32302f)]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:#282828"
format = '[[  $time ](fg:#ebdbb2 bg:#282828)]($style)'

