format = """
[░▒▓](#a9b665)\
[ 󰣇 ](bg:#a9b665 fg:#585a36)\
[](bg:#89b482 fg:#a9b665)\
$directory\
[](fg:#89b482 bg:#d8a657)\
$git_branch\
$git_status\
[](fg:#d8a657 bg:#3c3836)\
$nodejs\
$rust\
$golang\
$php\
[](fg:#3c3836 bg:#282828)\
$time\
[ ](fg:#282828)\n$character"""

[directory]
style = "fg:#475d44 bg:#89b482"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "bg:#d8a657"
format = '[[ $symbol $branch ](fg:#795f34 bg:#d8a657)]($style)'

[git_status]
style = "bg:#d8a657"
format = '[[($all_status$ahead_behind )](fg:#795f34 bg:#d8a657)]($style)'

[nodejs]
symbol = ""
style = "bg:#3c3836"
format = '[[ $symbol ($version) ](fg:#b8bb26 bg:#3c3836)]($style)'

[rust]
symbol = ""
style = "bg:#3c3836"
format = '[[ $symbol ($version) ](fg:#d3869b bg:#3c3836)]($style)'

[golang]
symbol = ""
style = "bg:#3c3836"
format = '[[ $symbol ($version) ](fg:#795f34 bg:#3c3836)]($style)'

[php]
symbol = ""
style = "bg:#3c3836"
format = '[[ $symbol ($version) ](fg:#8ec07c bg:#3c3836)]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:#282828"
format = '[[  $time ](fg:#ebdbb2 bg:#282828)]($style)'

