##### Enable true colors #####
set -g default-terminal "tmux-256color"

#### Leader Key #####
unbind C-b
set -g prefix F12
bind-key F12 send-prefix

##### Basics #####
set -g mouse on
set -g history-limit 10000
set -g renumber-windows on
setw -g base-index 1
setw -g pane-base-index 1
set -s escape-time 0
set -g repeat-time 500

##### Status bar #####
set-option -g status on
set-option -g status-position top
set -g status-style 'bg=#3C3836,fg=#DDC7A1'
set-option -g status-left '#[fg=colour233,bg=#89B482] #S '
set-option -g status-right '#[fg=colour256,bg=colour240,bold] %H:%M #[fg=#45403D,bg=colour214,bold] #h '
set -g status-justify centre

set -g window-status-format " #I:#W "
set -g window-status-current-format "#[fg=#3C3836, bg=colour179, italics, bold] #I:#W "

##### Pane Borders #####
set -g pane-border-style fg=#DDC7A1
set -g pane-active-border-style fg=#D8A657

##### Popup Styles #####
set -g popup-style bg=#32302f
set -g popup-border-style fg=#e78a4e,bg=#1e1e2e
set -g popup-border-lines rounded

##### Copy Mode & Messages #####
setw -g mode-style bg=colour237,fg=colour109
set -g message-style bg=colour237,fg=colour109
setw -g mode-keys vi
bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-selection-and-cancel
bind -T copy-mode-vi Escape send-keys -X cancel

##### Vim-style Pane Movement #####
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
bind -r C-h resize-pane -L 5
bind -r C-j resize-pane -D 5
bind -r C-k resize-pane -U 5
bind -r C-l resize-pane -R 5

##### Splitting Panes #####
bind '|' split-window -h -c "#{pane_current_path}"
bind '-' split-window -v -c "#{pane_current_path}"
unbind '"'
unbind %

##### Windows #####
bind c new-window
bind X kill-window
bind n next-window
bind p previous-window
bind w choose-window
bind r command-prompt -I "#W" "rename-window '%%'"

##### Panes #####
bind x kill-pane
bind z resize-pane -Z
bind q display-panes

##### Sessions #####
bind s choose-session
bind d detach-client

##### Reload Config #####
bind R source-file ~/.config/tmux/tmux.conf \; display "Config Reloaded!"

