# Keyboard media keys (mpc)
bindl = , XF86AudioPlay, exec, mpc toggle
bindl = , XF86AudioStop, exec, mpc stop
bindl = , XF86AudioNext, exec, mpc next
bindl = , XF86AudioPrev, exec, mpc previous

# Laptop multimedia keys for volume and LCD brightness (with notifications)
bindel = ,XF86AudioRaiseVolume, exec, ~/.local/bin/volume raise
bindel = ,XF86AudioLowerVolume, exec, ~/.local/bin/volume lower
bindel = ,XF86AudioMute, exec, ~/.local/bin/volume mute-toggle
bindel = ,XF86AudioMicMute, exec, ~/.local/bin/volume mic-mute-toggle
bindel = ,XF86MonBrightnessUp, exec, ~/.local/bin/brightness raise
bindel = ,XF86MonBrightnessDown, exec, ~/.local/bin/brightness lower

# Requires playerctl
bindl = , XF86AudioNext, exec, playerctl next
bindl = , XF86AudioPause, exec, playerctl play-pause
bindl = , XF86AudioPlay, exec, playerctl play-pause
bindl = , XF86AudioPrev, exec, playerctl previous
