# Close window
bindd = SUPER, W, "Close window", killactive

# Control tiling
bindd = SUPER, P, "Toggle pseudotile", pseudo
bindd = SUPER SHIFT, V, "Toggle float", togglefloating
bindd = , F11, "Toggle fullscreen", fullscreen, 0

# Move focus with mainMod + arrow keys
bindd = SUPER, left, "Focus left", movefocus, l
bindd = SUPER, right, "Focus right", movefocus, r
bindd = SUPER, up, "Focus up", movefocus, u
bindd = SUPER, down, "Focus down", movefocus, d

# Switch workspaces with mainMod + [0-9]
bindd = SUPER, code:10, "Workspace 1", workspace, 1
bindd = SUPER, code:11, "Workspace 2", workspace, 2
bindd = SUPER, code:12, "Workspace 3", workspace, 3
bindd = SUPER, code:13, "Workspace 4", workspace, 4
bindd = SUPER, code:14, "Workspace 5", workspace, 5
bindd = SUPER, code:15, "Workspace 6", workspace, 6
bindd = SUPER, code:16, "Workspace 7", workspace, 7
bindd = SUPER, code:17, "Workspace 8", workspace, 8
bindd = SUPER, code:18, "Workspace 9", workspace, 9

# Move active window to a workspace with mainMod + SHIFT + [0-9]
bindd = SUPER SHIFT, code:10, "Move to workspace 1", movetoworkspace, 1
bindd = SUPER SHIFT, code:11, "Move to workspace 2", movetoworkspace, 2
bindd = SUPER SHIFT, code:12, "Move to workspace 3", movetoworkspace, 3
bindd = SUPER SHIFT, code:13, "Move to workspace 4", movetoworkspace, 4
bindd = SUPER SHIFT, code:14, "Move to workspace 5", movetoworkspace, 5
bindd = SUPER SHIFT, code:15, "Move to workspace 6", movetoworkspace, 6
bindd = SUPER SHIFT, code:16, "Move to workspace 7", movetoworkspace, 7
bindd = SUPER SHIFT, code:17, "Move to workspace 8", movetoworkspace, 8
bindd = SUPER SHIFT, code:18, "Move to workspace 9", movetoworkspace, 9

# Swap active window with the one next to it with mainMod + SHIFT + arrow keys
bindd = SUPER SHIFT, left, "Swap left", swapwindow, l
bindd = SUPER SHIFT, right, "Swap right", swapwindow, r
bindd = SUPER SHIFT, up, "Swap up", swapwindow, u
bindd = SUPER SHIFT, down, "Swap down", swapwindow, d

# Resize active window
bindd = SUPER, minus, "Resize narrow", resizeactive, -100 0
bindd = SUPER, equal, "Resize wide", resizeactive, 100 0
bindd = SUPER SHIFT, minus, "Resize short", resizeactive, 0 -100
bindd = SUPER SHIFT, equal, "Resize tall", resizeactive, 0 100

# Move workspace between monitors
bindd = SUPER CTRL, LEFT, "Move workspace to left monitor", movecurrentworkspacetomonitor, l
bindd = SUPER CTRL, RIGHT, "Move workspace to right monitor", movecurrentworkspacetomonitor, r


# Scroll through existing workspaces with mainMod + scroll
bind = SUPER, mouse_down, workspace, e+1
bind = SUPER, mouse_up, workspace, e-1

# Move/resize windows with mainMod + LMB/RMB and dragging
bindm = SUPER, mouse:272, movewindow
bindm = SUPER, mouse:273, resizewindow

