# Launching
bindd = SUPER, space, "App launcher", exec, rofi -show drun
bindd = SUPER, Q, "Control panel", exec, ~/.local/bin/menus/control-panel

# Aesthetics
bindd = SUPER SHIFT, SPACE, "Toggle waybar", exec, pkill -SIGUSR1 waybar
bindd = SUPER CTRL, SPACE, "Wallpaper picker", exec, ~/.local/bin/menus/wallpaper-picker

# Notifications
bindd = SUPER, comma, "Dismiss one notification", exec, makoctl dismiss
bindd = SUPER SHIFT, comma, "Dismiss all notifications", exec, makoctl dismiss --all
bindd = SUPER CTRL, comma, "Toggle DND mode", exec, ~/.local/bin/toggle-dnd

# Power menu controls lock, suspend, relaunch, restart, shutdown
bindd = SUPER, ESCAPE, "Power menu", exec, ~/.local/bin/menus/power-menu

# Toggle idling
bindd = SUPER CTRL, I, "Toggle idle inhibit", exec, ~/.local/bin/toggle-idle

# Screenshots
bindd = , PRINT, "Screenshot menu", exec, ~/.local/bin/menus/screenshot

# Screenrecords
bindd = ALT, PRINT, "Screenrecord menu", exec, ~/.local/bin/menus/screenrecord

# Color picker
bindd = SUPER, PRINT, "Color picker", exec, hyprpicker -a

# Clipboard Manager
bindd = SUPER, V, "Clipboard manager", exec, foot -o 'font=SF Mono:size=12' --app-id=clipse -e clipse

# Keybindings
bindd = SUPER SHIFT, K, "Keybindings", exec, ~/.local/bin/menus/keybindings

# Nerd fonts selector
bindd = SUPER CTRL, N, "Nerd font selector", exec, rofi -modi nerdy -show nerdy -theme $HOME/.config/rofi/nerdfont-selector.rasi

# Network launcher
bindd = SUPER, N, "WiFi menu", exec, ~/.local/bin/menus/wifi

# Scratchpads
bindd = SUPER, grave, "Terminal scratchpad", exec, ~/.local/bin/scratchpad term scratchpad-term "uwsm app -- foot --title=scratchpad-term"
bindd = SUPER, apostrophe, "Notes scratchpad", exec, ~/.local/bin/scratchpad notes scratchpad-notes "uwsm app -- foot --title=scratchpad-notes -e nvim -u $HOME/.config/nvim/lean.lua $HOME/notes/notes.md"
bindd = SUPER, A, "Cody scratchpad", exec, ~/.local/bin/scratchpad cody scratchpad-cody "uwsm app -- foot --title=scratchpad-cody -o 'font=SF Mono:size=12' -e /home/asif/Projects/lumen/cody/.venv/bin/python -m cody"
bindd = SUPER, C, "OpenCode scratchpad", exec, ~/.local/bin/scratchpad opencode scratchpad-opencode "uwsm app -- foot --title=scratchpad-opencode -o 'font=SF Mono:size=12' -e env OPENCODE_CONFIG=/home/asif/.config/jarvis/opencode.json /home/asif/.opencode/bin/opencode ~"
