# Launching
bind = SUPER, space, exec, rofi -show drun

# Aesthetics
bind = SUPER SHIFT, SPACE, exec, pkill -SIGUSR1 waybar
bind = SUPER CTRL, SPACE, exec, ~/.local/bin/rofi-wallpaper-picker

# Notifications
bind = SUPER, comma, exec, makoctl dismiss
bind = SUPER SHIFT, comma, exec, makoctl dismiss --all
bind = SUPER CTRL, comma, exec, makoctl mode -t do-not-disturb && makoctl mode | grep -q 'do-not-disturb' && notify-send "Silenced notifications" || notify-send "Enabled notifications"

# Power menu controls lock, suspend, relaunch, restart, shutdown
bind = SUPER, ESCAPE, exec, ~/.local/bin/rofi-power-menu-2

# Toggle idling
bind = SUPER CTRL, I, exec, ~/.local/bin/toggle-idle

# Screenshots
bind = , PRINT, exec, ~/.local/bin/rofi-screenshot-2

# Screenrecords
bind = ALT, PRINT, exec, ~/.local/bin/rofi-screenrecord

# Color picker
bind = SUPER, PRINT, exec, hyprpicker -a

# Clipboard Manager
bind = SUPER, V, exec, kitty --override font_size=12 --class clipse -e clipse

# Nerd fonts selector
bind = SUPER CTRL, N, exec, rofi -modi nerdy -show nerdy -theme $HOME/.config/rofi/nerdfont-selector.rasi

# Scratchpads
bind = SUPER, grave, exec, bash -lc 'hyprctl clients | rg -q "title: scratchpad-term" || uwsm app -- ghostty --title=scratchpad-term; hyprctl dispatch togglespecialworkspace term'
bind = SUPER SHIFT, grave, movetoworkspacesilent, special:term
bind = SUPER CTRL, grave, exec, uwsm app -- ghostty --title=scratchpad-term

bind = SUPER, apostrophe, exec, bash -lc 'hyprctl clients | rg -q "title: scratchpad-notes" || uwsm app -- ghostty --title=scratchpad-notes -e nvim "$HOME/notes/scratchpad.md"; hyprctl dispatch togglespecialworkspace notes'
bind = SUPER SHIFT, apostrophe, movetoworkspacesilent, special:notes
bind = SUPER CTRL, apostrophe, exec, uwsm app -- ghostty --title=scratchpad-notes -e nvim "$HOME/notes/scratchpad.md"
