space        cycle pause; script-binding uosc/flash-pause-indicator
right        seek  5
left         seek -5
shift+right  seek  30; script-binding uosc/flash-timeline
shift+left   seek -30; script-binding uosc/flash-timeline
m            no-osd cycle mute; script-binding uosc/flash-volume
up           no-osd add volume  10; script-binding uosc/flash-volume
down         no-osd add volume -10; script-binding uosc/flash-volume
[            no-osd add speed -0.25; script-binding uosc/flash-speed
]            no-osd add speed  0.25; script-binding uosc/flash-speed
\            no-osd set speed 1; script-binding uosc/flash-speed
>            script-binding uosc/next; script-message-to uosc flash-elements top_bar,timeline
<            script-binding uosc/prev; script-message-to uosc flash-elements top_bar,timeline
n            add chapter 1; script-binding uosc/flash-timeline
MBTN_LEFT    cycle pause; script-binding uosc/flash-pause-indicator
MBTN_RIGHT   script-binding uosc/menu
TAB          script-binding uosc/toggle-ui
c            script-binding uosc/chapters
p            script-binding uosc/items


s screenshot video
S screenshot subtitles
Ctrl+s screenshot window

a cycle audio
v cycle sub-visibility
j cycle sub
J cycle sub down

Alt+LEFT add sub-delay -0.1
Alt+RIGHT add sub-delay 0.1

Ctrl+LEFT add audio-delay -0.1
Ctrl+RIGHT add audio-delay 0.1

q quit-watch-later
Q quit
