LEFT seek -5
RIGHT seek 5
UP seek 60
DOWN seek -60

Shift+LEFT seek -1 exact
Shift+RIGHT seek 1 exact

[ add speed -0.1
] add speed 0.1
BS set speed 1.0

s screenshot video
S screenshot subtitles
Ctrl+s screenshot window

a cycle audio
v cycle sub-visibility
j cycle sub
J cycle sub down

Alt+LEFT add sub-delay -0.1
Alt+RIGHT add sub-delay 0.1

Ctrl+LEFT add audio-delay -0.1
Ctrl+RIGHT add audio-delay 0.1

q quit-watch-later
Q quit

# uosc bindings
MBTN_LEFT  cycle pause
MBTN_RIGHT script-binding uosc/menu
TAB        script-binding uosc/toggle-ui
c          script-binding uosc/chapters
p          script-binding uosc/items
