# Learn how to configure Hyprland: https://wiki.hyprland.org/Configuring/

env = XCURSOR_THEME, Bibata-Modern-Classic
env = XCURSOR_SIZE, 26

source = ~/.config/hypr/monitors.conf
source = ~/.config/hypr/autostart.conf
source = ~/.config/hypr/bindings/media.conf
source = ~/.config/hypr/bindings/tiling.conf
source = ~/.config/hypr/bindings/utilities.conf
source = ~/.config/hypr/envs.conf
source = ~/.config/hypr/looknfeel.conf
source = ~/.config/hypr/input.conf
source = ~/.config/hypr/windows.conf
source = ~/.config/hypr/hyprfocus.conf

# Application bindings
$terminal = uwsm app -- ghostty
$browser = uwsm app -- chromium --new-window --ozone-platform=wayland --disable-session-crashed-bubble
$browser2 = uwsm app -- firefox
$webapp = $browser --app

bind = SUPER, return, exec, $terminal
bind = SUPER, B, exec, $browser2

bind = SUPER, Y, exec, $webapp="https://youtube.com/"
bind = SUPER SHIFT, G, exec, $webapp="https://web.whatsapp.com/"
bind = SUPER ALT, G, exec, $webapp="https://messages.google.com/web/conversations"

input {
  # Change speed of keyboard repeat
  repeat_rate = 40
  repeat_delay = 600

  # Increase sensitity for mouse/trackpack (default: 0)
  # sensitivity = 0.35

  touchpad {
    # Use natural (inverse) scrolling
    # natural_scroll = true

    # Use two-finger clicks for right-click instead of lower-right corner
    # clickfinger_behavior = true

    # Control the speed of your scrolling
    scroll_factor = 0.4
  }
}

# Scroll faster in the terminal
# windowrule = scrolltouchpad 1.5, class:kitty
