source = $HOME/.config/hypr/colors.conf

$accent = $primary
$accentAlpha = $primaryContainer
$font = SF Pro Display
$font_bold = SF Pro Display Bold
$font_black = SF Pro Display Black
$font_handwritten = New York Small

# GENERAL
general {
  hide_cursor = true
}

# BACKGROUND
background {
  monitor =
  path = $image
  blur_passes = 2
  color = $background
}

# LAYOUT
# label {
#   monitor =
#   text = Layout: $LAYOUT
#   color = $text
#   font_size = 25
#   font_family = $font
#   position = 30, -30
#   halign = left
#   valign = top
# }

# TIME
label {
  monitor =
  text = $TIME
  color = $primary_container
  font_size = 80
  font_family = $font_bold
  position = 0, -150
  halign = center
  valign = top
}

# DATE
label {
  monitor =
  text = cmd[update:43200000] date +"%A, %d %B %Y"
  color = $primary_container
  font_size = 25
  font_family = $font_bold
  position = 0, -280
  halign = center
  valign = top
}

# FORTUNE
label {
  monitor =
  text = cmd[update:600000] sh -c 'fortune -s | sed -e "s/&/\\&amp;/g" -e "s/</\\&lt;/g" -e "s/>/\\&gt;/g"'
  color = rgba(200, 200, 200, 0.8)
  font_size = 19
  font_family = $font_handwritten
  position = 0, 90
  halign = center
  valign = bottom
}

# USER AVATAR
image {
  monitor =
  path = ~/.face
  size = 150
  border_color = rgba(0, 0, 0, 0)
  position = 0, 50
  halign = center
  valign = center
}

# INPUT FIELD
input-field {
  monitor =
  size = 500, 60
  outline_thickness = 0
  dots_size = 0.2
  dots_spacing = 0.4
  dots_center = true
  outer_color = $primary
  inner_color = $background
  font_color = $on_background
  fade_on_empty = false
  placeholder_text = Password
  hide_input = false
  check_color = $accent
  fail_color = $error
  fail_text = <i>$FAIL <b>($ATTEMPTS)</b></i>
  capslock_color = $error
  position = 0, -100
  halign = center
  valign = center
}
