# See https://wiki.hyprland.org/Configuring/Monitors/

# Use single default monitor (see all monitors with: hyprctl monitors)
# Format: monitor = [port], resolution, position, scale

# Example for fractional scaling
# monitor=,preferred,auto,1.666667

# Example for Framework 13 w/ 6K XDR Apple display
monitor = eDP-1, preferred, auto, 1
monitor = HDMI-A-1, preferred, auto, 1
