# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
windowrule = match:class .*, suppress_event maximize

# Force chromium into a tile to deal with --app bug
windowrule = match:class ^(Chromium)$, tile on

# Workspace placement
windowrule = match:class ^(ghostty|com.mitchellh.ghostty|kitty)$, workspace 2
windowrule = match:class ^(Chromium|chromium|google-chrome|google-chrome-unstable|firefox|zen)$, workspace 3

# Float and center settings and previews
windowrule = match:class ^(blueberry.py|Wiremix|Nmtui|org.gnome.NautilusPreviewer|Omarchy|Bluetuith)$, float on, size (monitor_w*0.25) (monitor_h*0.5), center on
windowrule = match:title ^(Extension:.*Bitwarden.*)$, float on, center on, size (monitor_w*0.25) (monitor_h*0.5)

# Float and center file pickers
windowrule =  match:class xdg-desktop-portal-gtk, match:title ^(Open.*Files?|Open Folder|Save.*Files?|All Files|Save), float on, size (monitor_w*0.40) (monitor_h*0.5)
windowrule = match:class Thunar, match:title ^(Rename .*)$, float on, center on
windowrule = match:class firefox, match:title Library, float on, center on, size (monitor_w*0.25) (monitor_h*0.5)
# Float and Center Clipboard Managers
windowrule = match:class ^(clipse.*)$, float on, center on, size 500 700
windowrule = match:class ^(localsend.*)$, float on, center on, size 500 700


# Just dash of opacity
windowrule = match:class .*, opacity 0.95 0.9
windowrule = match:class ^(Chromium|chromium|google-chrome|google-chrome-unstable|firefox|zen)$, opacity 0.99 0.97
windowrule = match:class ^(zoom|vlc|mpv|org.kde.kdenlive|com.obsproject.Studio|com.github.PintaProject.Pinta|imv|org.gnome.NautilusPreviewer)$, opacity 1.0 1.0
windowrule = match:initial_title ^(youtube.com_/|netflix.com_/)$, opacity 1.0 1.0 # Youtube

# Try to hide the android emulator sidebar
windowrule = match:class ^(Emulator)$, match:title ^(Emulator)$, opacity 0.0 0.0
windowrule = move (cursor_x-(window_w*0.5)) (cursor_y-(window_h*0.5)), match:class kitty  # Move kitty to the center of the cursor

# Scratchpad windows
windowrule = match:class ^(scratchpad-term)$, workspace special:term silent
windowrule = match:class ^(scratchpad-term)$, float on, center on, size (monitor_w*0.65) (monitor_h*0.65)

windowrule = match:class ^(scratchpad-notes)$, workspace special:notes silent
windowrule = match:class ^(scratchpad-notes)$, float on, size (monitor_w*0.30) (monitor_h*0.75)

windowrule = match:class ^(scratchpad-cody)$, workspace special:cody silent
windowrule = match:class ^(scratchpad-cody)$, float on, size (monitor_w*0.30) (monitor_h*0.60)

windowrule = match:class ^(scratchpad-opencode)$, workspace special:opencode silent
windowrule = match:class ^(scratchpad-opencode)$, float on, size (monitor_w*0.30) (monitor_h*0.75)
