# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
windowrule = suppressevent maximize, class:.*

# Force chromium into a tile to deal with --app bug
windowrule = tile, class:^(Chromium)$

# Float and center settings and previews
windowrule = float, class:^(blueberry.py|Wiremix|Nmtui|org.gnome.NautilusPreviewer|Omarchy|Bluetuith)$
windowrule = center, class:^(blueberry.py|Wiremix|Nmtui|org.gnome.NautilusPreviewer|Omarchy|Bluetuith)$
windowrule = size 1080 540, class:^(blueberry.py|Wiremix|org.gnome.NautilusPreviewer|com.gabm.satty|Bluetuith)$
windowrule = size 700 600, class:^(Nmtui)$

# Float and center file pickers
windowrule = float, class:xdg-desktop-portal-gtk, title:^(Open.*Files?|Open Folder|Save.*Files?|All Files|Save)
windowrule = center, class:xdg-desktop-portal-gtk, title:^(Open.*Files?|Open Folder|Save.*Files?|All Files|Save)
windowrule = size 1120 630, class:xdg-desktop-portal-gtk, title:^(Open.*Files?|Open Folder|Save.*Files?|All Files|Save)$
windowrule = float, class:com.gabm.satty
windowrule = center, class:com.gabm.satty
# Float Steam, fullscreen RetroArch
windowrule = float, class:^(steam)$
windowrule = fullscreen, class:^(com.libretro.RetroArch)$
# Float and Center Clipboard Managers
windowrule = float, class:^(clipse.*)$
windowrule = center, class:^(clipse.*)$
windowrule = size 500 700, class:^(clipse.*)$


# Just dash of opacity
windowrule = opacity 0.95 0.9, class:.*
windowrule = opacity 1 0.99, class:^(Chromium|chromium|google-chrome|google-chrome-unstable)$
windowrule = opacity 1 1, initialTitle:^(youtube.com_/)$ # Youtube
windowrule = opacity 1 1, class:^(zoom|vlc|mpv|org.kde.kdenlive|com.obsproject.Studio|com.github.PintaProject.Pinta|imv|org.gnome.NautilusPreviewer)$
windowrule = opacity 1 1, class:^(com.libretro.RetroArch|steam)$
windowrule = opacity 1 1, initialTitle:^(netflix.com_/)$

# Fix some dragging issues with XWayland
windowrule = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0

# Try to hide the android emulator sidebar
windowrulev2 = opacity 0.0 0.0, class:^(Emulator)$, title:^(Emulator)$

