# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
windowrule = match:class .*, suppress_event maximize
windowrule = match:class .*, opacity 0.88 0.85

windowrule = match:class vlc, opacity 1 0.82
windowrule = match:initial_title netflix.com_/, opacity 1 0.82


# Float and center settings and previews
windowrule = match:class ^(blueberry.py|Wiremix|Nmtui|org.gnome.NautilusPreviewer|Omarchy|Bluetuith)$, float on, size (monitor_w*0.25) (monitor_h*0.5), center on, animation slide

# Phone mirror (scrcpy)
windowrule = match:class scrcpy, float on, size 360 800, move 10 (monitor_h-800-10), opacity 1 1
windowrule = match:class ^(nwg-look|nwg-launcher)$, float on, center on, size 800 600, animation slide
windowrule = match:title ^(Extension:.*Bitwarden.*)$, float on, center on, size (monitor_w*0.25) (monitor_h*0.5), animation slide
# Float and center file pickers
windowrule =  match:class xdg-desktop-portal-gtk, match:title ^(Open.*|Open Folder|Save.*Files?|All Files|Save), float on, size (monitor_w*0.40) (monitor_h*0.5), animation slide
windowrule = match:class Thunar, match:title ^(Rename .*)$, float on, center on, animation slide
windowrule = match:class firefox, match:title Library, float on, center on, size (monitor_w*0.25) (monitor_h*0.5), animation slide
# Float and Center Clipboard Managers
windowrule = match:class ^(clipse.*)$, float on, center on, size 500 700, animation slide
# Float and Center other utility apps
windowrule = match:class ^(localsend.*)$, float on, center on, size 500 700, animation slide

# Keybindings
windowrule = match:title ^(hypr-binds)$, float on, center on, size 900 600, animation slide

# Scratchpad windows
windowrule = match:initial_title ^(scratchpad-term)$, workspace special:term, no_anim 1, float on, center on, size (monitor_w*0.65) (monitor_h*0.65)
windowrule = match:initial_title ^(scratchpad-notes)$, workspace special:notes, no_anim 1, float on, size (monitor_w*0.25) (monitor_h*0.70), move 10 (monitor_h*0.30-10)
windowrule = match:initial_title ^(scratchpad-cody)$, workspace special:cody, no_anim 1, float on, size (monitor_w*0.25) (monitor_h*0.70), move 10 (monitor_h*0.30-10)
windowrule = match:initial_title ^(scratchpad-opencode)$, workspace special:opencode, no_anim 1, float on, size (monitor_w*0.30) (monitor_h*0.75), move 10 (monitor_h*0.25-10)
