timeline_size=30
timeline_persistency=paused
controls=menu,gap,<video,audio>subtitles,<has_many_audio>audio,<has_many_video>video,<has_many_edition>editions,<stream>stream-quality,gap,space,fullscreen
volume=right
pause_indicator=manual
autoload=yes
