timeline_size=40
timeline_persistency=paused
controls=menu,gap,subtitles,space,audio,space,shuffle,loop-playlist,space,prev,items,next,space,fullscreen
volume=right
top_bar=always
pause_indicator=flash
autoload=yes
